[[marvel]]
=== Marvel for Monitoring

https://www.elastic.co/guide/en/marvel/current/index.html[Marvel] enables 
you to easily monitor Elasticsearch through Kibana. You can view your 
cluster’s health and performance in real time as well as analyze 
past cluster, index, and node metrics. 

While you can access a large number of statistics through the APIs described 
in this chapter, they only show you what's going on at a single point in time.
Knowing memory usage at this instant is helpful, but knowing
memory usage _over time_ is much more useful. Marvel queries and aggregates 
the metrics so you can visualize your cluster's 
behavior over time, which makes it easy to spot trends. 

As your cluster grows, the output from the stats APIs can get truly hairy.
Once you have a dozen nodes, let alone a hundred, reading through stacks of JSON
becomes very tedious. Marvel lets you explore the data interactively and
makes it easy to zero in on what's going on with particular nodes or indices.

Marvel uses the same stats APIs that are available to you--it does not expose 
any statistics that you can't access through the APIs.  However, Marvel greatly 
simplifies the collection and visualization of those statistics.

Marvel is free to use (even in production!), so you should definitely try it out!
For installation instructions, see 
https://www.elastic.co/guide/en/marvel/current/getting-started.html[Getting Started with Marvel].
