[[getting-started]]
= Getting started

[partintro]
--
Elasticsearch is a real-time distributed search and analytics engine. It
allows you to explore your data at a speed and at a scale never before
possible.

It is used for full text search, structured search, analytics, and all three
in any combination:

*   Wikipedia uses Elasticsearch to provide full text search with highlighted
    search snippets, and _search-as-you-type_ and _did-you-mean_ suggestions.

*   The Guardian uses Elasticsearch to combine visitor logs with social
    network data to provide real-time feedback to their editors about
    public response to new articles.

*   StackOverflow combines full text search with geolocation queries and uses
    _more-like-this_ to find related questions and answers.

*   GitHub uses Elasticsearch to query 130 billion lines of code.

*   Goldman Sachs uses Elasticsearch to index 5TB of log data every day.

*   A number of investment banks use Elasticsearch to analyze movements in the stock market.

But Elasticsearch is not just for mega-corporations. It has enabled many
startups like DataDog and Klout to prototype ideas and to turn them into
scalable solutions. Elasticsearch can run on your laptop, or scale out to
hundreds of servers and petabytes of data.

No individual part of Elasticsearch is new or revolutionary. Full text search
has been done before, as have analytics systems and distributed databases. The
revolution is how Elasticsearch combines these individually useful parts into a
single, coherent, real-time application. Elasticsearch is easy to learn
but can keep pace as your skills and needs grow.

If you are picking up this book, it is because you have data, and there is no
point in having data unless you plan to *do something* with it.

Unfortunately, most databases are astonishingly inept at extracting something useful
from your data. Sure, databases can filter by timestamp or exact values,
but can they perform full-text search, handle synonyms and score documents by
relevance?  Can they generate analytics and aggregations from the same data?
Most importantly, can they do this in real-time without big batch processing
jobs?

This is what sets Elasticsearch apart: Elasticsearch encourages you to explore
gain insight from your data, rather than letting it rot in a warehouse because it is
too difficult to query.

Elasticsearch is your new best friend.
--

