ifndef::es_build[= placeholder3]

[[aggregations]]
= 聚合

[partintro]
--
在这之前，本书致力于搜索。((("searching", "search versus aggregations")))((("aggregations")))  通过搜索，如果我们有一个查询并且希望找到匹配这个查询的文档集，就好比在大海捞针。

通过聚合，我们会得到一个数据的概览。我们需要的是分析和总结全套的数据而不是寻找单个文档：

// Popular manufacturers? Unusual clumps of needles in the haystack?
- 在大海里有多少针？
- 针的平均长度是多少？
- 按照针的制造商来划分，针的长度中位值是多少？
- 每月加入到海中的针有多少？

聚合也可以回答更加细微的问题：

- 你最受欢迎的针的制造商是什么？
- 这里面有异常的针么？

聚合允许我们向数据提出一些复杂的问题。虽然功能完全不同于搜索，但它使用相同的数据结构。这意味着聚合的执行速度很快并且就像搜索一样几乎是实时的。

这对报告和仪表盘是非常强大的。你可以实时显示你的数据，让你立即回应，而不是对你的数据进行汇总（ _需要一周时间去运行的 Hadoop 任务_ ），您的报告随着你的数据变化而变化，而不是预先计算的、过时的和不相关的。

最后，聚合和搜索是一起的。((("aggregations", "operating alongside search requests"))) 这意味着你可以在单个请求里同时对相同的数据进行搜索/过滤和分析。并且由于聚合是在用户搜索的上下文里计算的，你不只是显示四星酒店的数量，而是显示匹配查询条件的四星酒店的数量。

聚合是如此强大以至于许多公司已经专门为数据分析建立了大型 Elasticsearch 集群。
--

include::301_Aggregation_Overview.asciidoc[]

include::302_Example_Walkthrough.asciidoc[]

include::303_Making_Graphs.asciidoc[]

include::304_Approximate_Aggregations.asciidoc[]

include::305_Significant_Terms.asciidoc[]

include::306_Practical_Considerations.asciidoc[]

