[[geoloc]]
= Geolocation

[partintro]
--
Gone are the days when we wander around a city with paper maps. Thanks to
smartphones, we now know exactly where we are all of the time, and we expect
websites to use that information.  I'm not interested in restaurants in
Greater London -- I want to know about restaurants within 5 minutes walk of my
current location.

But geolocation is only one part of the puzzle.  The beauty of Elasticsearch
is that it allows you to combine geolocation with full text search, structured
search, and analytics.

For instance: show me restaurants that mention _vitello tonnato_, are within 5
minutes walk, and are open at 11pm, and rank them by a combination of user
rating, distance and price. Another example: show me a map of holiday rental
properties available in August throughout the city, and calculate the average
price per zone.

Elasticsearch offers two ways of representing geolocations: latitude-longitude
points using the `geo_point` field type, and complex shapes defined in
http://en.wikipedia.org/wiki/GeoJSON[GeoJSON], using the `geo_shape` field
type.

Geo-points allow you to find points within a certain distance of another
point, to calculate distances between two points for sorting or relevance
scoring, or to aggregate into a grid to display on a map.  Geo-shapes, on the
other hand, are used purely for filtering.  They can be used to decide whether
two shapes overlap or not, or whether one shape completely contains other
shapes.

--


