[[terms_filter]]
==== Terms filter

The `terms` filter is like the `term` filter but allows you to check for
multiple values at once, much like the `IN` operator in SQL.  By default,
it checks whether the field contains *ANY* of the listed values:

    { "terms": { "status": [ "active", "pending" ] }}

Fields may contain multiple values, so you can use the `execution` option
to check whether the field contains *ALL* of the listed values:

    {
        "terms": {
            "execution": "and",
            "tags":      [ "elasticsearch", "nosql" ]
        }
    }

[NOTE]
====
The default value for `execution` is `plain`. It can also be set to `bool`,
which (like `plain`) checks for ANY of the listed values, but it has
different performance characteristics.
The final result of the `plain` query is cached, while under `bool` execution,
the result for each individual term is cached.  So if you regularly
filter on the same combination of terms, then `plain` execution is preferred.
But if the combination of terms varies, then the `bool` execution might
be faster.
====
