[[geo-distance]]
=== Geo Distance Filter

The `geo_distance` filter draws a circle around the specified location and
finds all documents((("geo_distance filter")))((("filtering", "by geo-points", "geo_distance filter"))) that have a geo-point within that circle:

[source,json]
---------------------
GET /attractions/restaurant/_search
{
  "query": {
    "filtered": {
      "filter": {
        "geo_distance": {
          "distance": "1km", <1>
          "location": { <2>
            "lat":  40.715,
            "lon": -73.988
          }
        }
      }
    }
  }
}
---------------------
<1> Find all `location` fields within `1km` of the specified point.
    See {ref}/common-options.html#distance-units[Distance Units] for
    a list of the accepted units.
<2> The central point can be specified as a string, an array, or (as in this
    example) an object. See <<lat-lon-formats>>.

A geo-distance calculation is expensive.  To optimize performance,
Elasticsearch draws a box around the circle and first uses the less expensive
bounding-box calculation to exclude as many documents as it can.  It runs
the geo-distance calculation on only those points that fall within the bounding
box.

TIP: Do your users really require an accurate circular filter to be applied to
their results?((("geo_bounding_box filter", "using instead of geo_distance"))) Using a rectangular <<geo-bounding-box,bounding box>> is much
more efficient than geo-distance and will usually serve their purposes just as
well.

==== Faster Geo-Distance Calculations

The distance between two points can be calculated using algorithms,
which trade performance for accuracy:((("distance", "calculating")))((("geo_distance filter", "faster geo_distance calculations")))

`arc`::

The slowest but most accurate is the `arc` calculation, which treats the world
as a sphere.((("arc distance calculation")))  Accuracy is still limited because the world isn't really a sphere.

`plane`::

The `plane` calculation, which((("plane distance calculation"))) treats the world as if it were flat, is faster
but less accurate. It is most accurate at the equator and becomes less
accurate toward the poles.

`sloppy_arc`::

So called because it uses the `SloppyMath` Lucene class to trade accuracy for speed,((("sloppy_arc distance calculation")))
the `sloppy_arc` calculation uses the
http://en.wikipedia.org/wiki/Haversine_formula[Haversine formula] to calculate
distance.((("Haversine formula (for distance)"))) It is four to five times as fast as `arc`, and distances are 99.9% accurate.
This is the default calculation.

You can specify a different calculation as follows:

[source,json]
---------------------
GET /attractions/restaurant/_search
{
  "query": {
    "filtered": {
      "filter": {
        "geo_distance": {
          "distance":      "1km",
          "distance_type": "plane", <1>
          "location": {
            "lat":  40.715,
            "lon": -73.988
          }
        }
      }
    }
  }
}
---------------------
<1> Use the faster but less accurate `plane` calculation.

TIP: Will your users really care if a restaurant is a few meters outside their specified radius? While some geo applications require great accuracy,
less-accurate but faster calculations will suit the majority of use cases just
fine.

[[geo-distance-range]]
==== geo_distance_range Filter

The only difference between the `geo_distance` and `geo_distance_range`
filters((("geo_distance_range filter")))((("filtering", "by geo-points", "geo_distance_range filter")))((("range filters", "geo_distance_range filter"))) is that the latter has a doughnut shape and excludes documents within
the central hole.

Instead of specifying a single `distance` from the center, you specify a
minimum distance (with `gt` or `gte`)  and maximum distance (with `lt` or
`lte`), just like a `range` filter:

[source,json]
---------------------
GET /attractions/restaurant/_search
{
  "query": {
    "filtered": {
      "filter": {
        "geo_distance_range": {
          "gte":    "1km", <1>
          "lt":     "2km", <1>
          "location": {
            "lat":  40.715,
            "lon": -73.988
          }
        }
      }
    }
  }
}
---------------------
<1> Matches locations that are at least `1km` from the center, and less than
    `2km` from the center.


