=== Creating an index

Up until now, we have created a new index by simply indexing a document
into it.  The index is created with the default settings, and new
fields are added to the type mapping using dynamic detection.

Now we need more control over the process: we want to ensure that the index
has been created with the correct number of primary shards, that analyzers
and mappings are set up *before* we index any data.

To do this, we have to create the index manually, passing in any settings
or type mappings in the request body, as follows:

[source,js]
--------------------------------------------------
PUT /my_index
{
    "settings": { ... any settings ... },
    "mappings": {
        "type_one": { ... any mappings ... },
        "type_two": { ... any mappings ... },
        ...
    }
}
--------------------------------------------------


In fact, you can prevent the automatic creation of indices by adding the
following setting to the `config/elasticsearch.yaml` file on each node:

[source,js]
--------------------------------------------------
action.auto_create_index: false
--------------------------------------------------


****
Later, we will discuss how you can use <<_index_templates_2>>
to pre-configure automatically created indices. This is particularly
useful when indexing log data, allowing you to roll over to a new
automatically created index every day.
****

=== Deleting an index

To delete an index, use the following request:

[source,js]
--------------------------------------------------
DELETE /my_index
--------------------------------------------------


You can delete multiple indices with:

[source,js]
--------------------------------------------------
DELETE loclahost:9200/index_one,index_two
DELETE /index_*
--------------------------------------------------


You can even delete *ALL* indices with:

[source,js]
--------------------------------------------------
DELETE /_all
--------------------------------------------------


You may want to disable the ability to delete all indices, by adding
this setting to your `config/elasticsearch.yaml` file:

[source,js]
--------------------------------------------------
action.disable_delete_all_indices: true
--------------------------------------------------


With this setting in effect, you will only be able to delete indices
by being explicit:

[source,js]
--------------------------------------------------
DELETE /index_one,index_two
--------------------------------------------------



