[[helper-queries]]
=== Helper queries

The _helper_ queries are simple, commonly used queries. Unlike most queries,
they have little to do with relevance.

[[match-all-query]]
==== `match_all` query

This simply matches all documents and returns a `_score` of 1 for all of them.
It is the default query that is run if no query is passed to a search request.
So these two search requests are equivalent:

    curl -XGET localhost:9200/_search


    curl -XGET localhost:9200/_search -d '
    {
        "query": {
            "match_all" : {}
        }
    }
    '

[[filtered-query]]
==== `filtered` query

The `filtered` query, as explained in <<query-structure>>, is used to combine
a filter with a query.

    {
        "filtered" : {
            "query" :  { ANY QUERY CLAUSE  },
            "filter" : { ANY FILTER CLAUSE }
        }
    }

It accepts a single filter clause and a single query clause. However,
you can pass it a <<bool-query,compound query>> or
<<compound-filters,compound filter>> which can contain multiple
sub-clauses:

    {
        "filtered" : {
            "query" :  {
                "bool": {
                    "should": [
                        { "match" : { "title" :  "quick brown fox" },
                        { "match" : { "body" :   "quick brown fox" }
                    ]
                }
            },
            "filter" : {
                "bool" : {
                    "must": [
                        { "term" :  { "status" :   "active" }},
                        { "term" :  { "featured" : true     }}
                    ]
                }
            }
        }
    }




