[[helper_queries]]
=== Helper queries

The _helper_ queries are simple, commonly used queries. Unlike most queries,
they have little to do with relevance.

[[match_all_query]]
==== `match_all` query

This simply matches all documents and returns a `_score` of 1 for all of them.
It is the default query that is run if no query is passed to a search request.
So these two search requests are equivalent:

    curl -XGET http://localhost:9200/_search


    curl -XGET http://localhost:9200/_search -d '
    {
        "query": {
            "match_all" : {}
        }
    }
    '

[[filtered_query]]
==== `filtered` query

The `filtered` query, as explained in <<query_structure>>, is used to combine
a filter with a query.

    {
        "filtered" : {
            "query" :  { ANY QUERY CLAUSE  },
            "filter" : { ANY FILTER CLAUSE }
        }
    }

It accepts a single filter clause and a single query clause. However,
you can pass it a <<compound_queries,compound query>> or
<<compound_filters, compound filter>> which can contain multiple
sub-clauses:

    {
        "filtered" : {
            "query" :  {
                "match" : { "title" :  "quick brown fox" }
            },
            "filter" : {
                "and" : [
                   { "term" :  { "status" :   "active" }},
                   { "term" :  { "featured" : true     }}
               ]
            }
        }
    }




