=== Using query clauses

Like the filter clauses, each query clause is a standalone element that
can be used wherever _query_context_ applies:

  * as the argument for any parameter in the Elasticsearch API called `filter`
  * in a compound query clause (such as the <<bool-query,`bool` query>>) which
    expects one or more query clauses
  * in any filter clause which accepts a `query` argument, such as the
    `query` filter

For instance, this  `match` query clause:

    { "match": { "title": "fox" }}

could be used as the argument to the `query` parameter in a `search` request,
as follows:

    curl -XGET http://localhost:9200/_search -d '
    {
        "query": { "match": { "title": "fox" }}
    }
    '

This simple `match` query could be combined with other query clauses using,
for instance, the compound <<bool-query,`bool` query>>:

    {
        "bool": {
            "should": [
                { "match": { "title": "fox" }},
                { "match": { "body":  "fox" }}
            ]
        }
    }

which could, again, be passed to the `query` parameter in a `search` request:

    curl -XGET http://localhost:9200/_search -d '
    {
        "query": {
            "bool": {
                "should": [
                    { "match": { "title": "fox" }},
                    { "match": { "body":  "fox" }}
                ]
            }
        }
    }
    '
