=== What is relevance?

When searching, documents are returned in a particular order.  They
could be sorted on the `last_modified` time, but the default is to sort
them from most relevant to least relevant. This relevance value is called
the `_score`.

Each query clause generates a `_score`. When multiple query clauses are
wrapped together using a compound query, the `_score` from each
of these query clauses is combined to calculate the final `_score`
for the document. How the `_score` is calculated for each query type
depends on the purpose of the query.

Typical factors that are taken into account with full text search
queries are:

Term frequency::
  How often does each term appear in the field? The more often, the more
  relevant.

Inverse document frequency::
  How often does each term appear in the index?  The more often, the *less*
  relevant.

Length norm::
  How long is the field? The longer it is, the less likely it is to be
  relevant.

We will discuss how relevance is calculated in more detail in <<boost>>.

That said, relevance is not just about full text search. It can equally be
applied to `yes|no` clauses where the more clauses that match, the more
relevant, or to geolocation queries, where closer is better.

