=== What is relevance?

The results of a query are returned in a particular order. They
could be sorted on the `last_modified` time, but the default is to sort
them from most relevant to least relevant.

The relevance of each document is represented by a positive floating point
number called the `_score` -- the higher the `_score`, the more relevant.

A query clause generates a `_score` for each document.  How that score
is calculated depends on the type of query clause -- different query
clauses are used for different purposes.

Typical factors that are taken into account with full text search
queries are:

Term frequency::
  How often does each term appear in the field? The more often, the more
  relevant.

Inverse document frequency::
  How often does each term appear in the index?  The more often, the *less*
  relevant.

Length norm::
  How long is the field? The longer it is, the less likely it is
  that words in the field will be relevant.

That said, relevance is not just about full text search. It can equally be
applied to `yes|no` clauses, where the more clauses that match, the more
relevant.

When multiple query clauses are combined using a compound query,
the `_score` from each of these query clauses is combined to calculate the
overall `_score` for the document.

We will discuss how relevance is calculated in more detail in <<boost>>.

