=== Talking to Elasticsearch

How you talk to Elasticsearch depends on whether you are using Java or not.

==== Java API

If you are using Java, then Elasticsearch provides two built-in clients
which you can use in your code:

Node client::
    The node client joins a local cluster as a _non-data node_. In other
    words, it doesn't hold any data itself, but it knows what data lives
    on which node in the cluster, and can forward requests directly
    to the correct node.

Transport client::
    The lighter weight transport client can be used to send requests to
    a remote cluster. It doesn't join the cluster itself, but simply
    forwards requests to a node in the cluster.

Both Java clients talk to the cluster over *port 9300*, using the native
Elasticsearch protocol.  The nodes in the cluster also communicate
with each other over port 9300. If this port is not open, then your nodes will
not be able to form a cluster.

[NOTE]
====
The Java client must be from the same version of Elasticsearch as the nodes,
otherwise they may not be able to understand each other.
====

==== RESTful API with JSON over HTTP

All other languages can use any simple HTTP client to communicate with
the cluster over *port 9200*. In fact, as you have seen above, you can
even talk to Elasticsearch from the command line, using the
`curl` command.

All requests consist of:

* an appropriate HTTP method: `GET`, `POST`, `PUT`, `HEAD` or `DELETE`
* the protocol and hostname of any node in the cluster,
  eg: `http://localhost:9200`
* the path of the resource you want to use, eg: `/_count`
* any optional query string parameters, eg `?pretty=true` will _pretty-print_
  the JSON response to make it easier to read
* a JSON encoded request body (if the request needs one)

For instance, to count the number of documents in the cluster, we could
use:

    curl -XGET 'http://localhost:9200/_count?pretty=true' -d '
    {
        "match_all": {}
    }
    '

All responses consist of:

* an HTTP status code, eg: `200 OK`
* a response body encoded in JSON (except for `HEAD` requests, which don't
  return a body)

The above `curl` request would respond with a JSON body like the
following:

    {
        "count" : 0,
        "_shards" : {
            "total" : 5,
            "successful" : 5,
            "failed" : 0
        }
    }

We don't see the HTTP headers in the response because we didn't ask `curl` to
display them. To see the headers, use the `curl` command with the `-D`
switch:

    curl -D - -XGET 'http://...'

We will use this `curl` format in all of our examples because it is easy to
read and easy to translate into a request using the HTTP library of your
choice.
