=== Distributed nature

Elasticsearch is built to be always available, and to scale with your needs.
Scale can come from buying bigger servers (_vertical scale_ or _scaling up_)
or buying more servers (_horizontal scale_ or _scaling out_).

While Elasticsearch can benefit from more powerful hardware, vertical
scale has its limits. Real scalability comes from horizontal scale
-- the ability to add more nodes to the cluster and to spread
load and reliability between them.  With most databases, scaling horizontally
usually requires a major overhaul of your application to take advantage
of these extra boxes.

Elasticsearch, however,  is _distributed_ by nature. In other
words, it natively knows how to use and manage multiple nodes to provide
scale and high availability.  This also means that your application
doesn't need to care about it.

As users, we can talk any node in the Elasticsearch cluster. That node knows
how to route the request to the nodes that hold the data we are interested in.
It is all managed transparently by Elasticsearch.

The easiest way to explain how the distributed nature of Elastisearch works, it
to demonstrate it.
