
=== Running multiple nodes

For demonstration purposes, we are going to start multiple Elasticsearch
nodes on the same machine. This is not recommended in production, but is fine
for our purposes. Multiple nodes can be run from the same directory,
with the same configuration and paths.

If you have followed the instructions above, then you are already running
an Elasticsearch node. To start another node, open a new terminal window,
change to the directory where you unpacked Elasticsearch, and type:

    ./bin/elasticsearch -f

In the output from the new node, you should see something like:

    [INFO ][cluster.service] [Harpy] detected_master [Rand, Daniel]

If, instead, you see a line like the following, then it means that your
nodes have not been able to detect each other:

    [INFO ][cluster.service] [Harpy] new_master [Harpy]


==== Troubleshooting

To ensure that your nodes can form a cluster, you need to check the following.
After making any changes to the configuration files, kill the existing nodes
with `Ctrl-C` and restart them.

===== Cluster name

All the nodes in our cluster must have the same name, which is configured
in `./config/elasticsearch.yml`. The default is:

    cluster.name: elasticsearch

You may want to change the name to avoid forming a cluster with other nodes
on the same network.

===== Firewall

By default, a node tries to bind to the public IP address of the
host machine. It uses port `9300` for communication between nodes, and port
`9200` for HTTP requests. If these ports are already being used, then it
will try ports `9301` to `9400` and `9201` to `9300` respectively.

Often, the public IP address will be protected by a firewall, which prevents
the nodes from communicating and forming a cluster.

Either you should open up ports 9300-9400 or you can force Elasticsearch
to just use `localhost`, which isn't usually protected by the firewall.
You can do this by adding the following line to `./config/elasticsearch.yml`:

    network.host: 127.0.0.1

Alternatively, you can set this temporarily by starting Elasticsearch as
follows:

    ./bin/elasticsearch -f -Des.network.host=127.0.0.1

===== Multicast

By default, new nodes detect an existing cluster using multicast.  Multicast
is enabled on most modern machines, but if your nodes are still unable
to detect each other, then you can try using unicast instead.

When using unicast, you need to provide one or more hostnames or IP addresses
that the node should try to contact.  For our purposes, you can add
the following line to `./config/elasticsearch.yml`:

    discovery.zen.ping.unicast.hosts: ["localhost"]


