=== What is Elasticsearch?

The ability to filter data by dates, postcodes or other exact values is a
solved problem -- any database can do it.

However, full text search -- processing a natural language query to find
the most relevant results in unstructured data -- is a much more complicated
undertaking. The few databases which support full text search either hand it
over entirely to a dedicated full text search engine, or do it badly.

[quote]
Elasticsearch is a search engine built on top of Apache Lucene.

So what is Lucene?

[quote,'http://lucene.apache.org/core/[lucene.apache.org/core]']
____
Apache Lucene(TM) is a high-performance, full-featured text search engine
library written entirely in Java.
____

Lucene is really, really powerful -- but it is just a library. If you want to
use Lucene, you need a degree in _information retrieval_, must work
entirely in Java and must tightly couple your code to the Lucene libraries.

Elasticsearch is based on Lucene, which means that it uses Lucene internally
for its indexing and search, and it excels at full text search.
However, it is much more than just Lucene and much more than ``just'' full
text search.

It is:

* a distributed document store where every field is indexed and
   searchable
* a distributed search engine with real-time analytics
* capable of scaling to hundreds of servers and terabytes of structured
  and unstructured data.

And it packages up all of this functionality into a standalone service
that your application can talk to via a simple API, using whichever
programming language you choose to use.

It is easy to get started with Elasticsearch. It ships with
sensible defaults and hides complicated search theory from beginners.
It just works, right out of the box. With minimal understanding,
you can soon become productive.

As your knowledge grows, you can leverage more of Elasticsearch's
advanced features. The entire engine is configurable and very flexible.
Pick and choose from the advanced features to tailor Elasticsearch to your
problem domain.

