=== What is Elasticsearch?

The ability to filter data by dates, postcodes or other exact values is a
solved problem -- any database can do it.

However, full text search -- processing a natural language query to find
the most relevant results in unstructured data -- is a much more complicated
undertaking. The few databases which support full text search either hand it
over entirely to a dedicated full text search engine, or do it badly.

[quote]
Elasticsearch is a search engine built on top of Apache Lucene.

So what is Lucene?

[quote,'http://lucene.apache.org/core/[lucene.apache.org/core]']
____
Apache Lucene(TM) is a high-performance, full-featured text search engine
library written entirely in Java.
____

Lucene is really really powerful. The problem with it is that it is just
a library. If you want to use it, you need to understand a lot about
_information retrieval_, Java is your only choice of programming language
and your code has to be tightly coupled with the Lucene libraries.

Elasticsearch is based on Lucene, which means that it uses Lucene internally
for its indexing and search, and it excels at full text search.
However, it is much more than just Lucene and much more than ``just'' full
text search.

It is a distributed document store where every field is indexed and
searchable; a distributed search engine with real-time analytics, capable
of scaling to hundreds of servers and terabytes of structured and unstructured
data. And it packages up all of this functionality into a standalone service
that your application can talk to via a simple API, whichever programming
language you choose to use.

It is easy to get started with Elasticsearch. It requires you to know just
enough to make use of the functionality you need. As your requirements grow,
so you learn more about the full feature set that Elasticsearch offers.


