

You have data, and you want to interrogate it to answer some question.
Perhaps you are trying to gain insight into your business by analyzing
metrics.  Or maybe you are just letting customers look through your product
catalogue.

How do you access your data?  A traditional databases can filter by date, postcode or
exact values. This is a solved problem. Any database can do it, and do it quickly.

But how about full text search?  Full text search must find results
in unstructured data using a natural language query, and then rank them by
'relevancy'. This is a task that modern databases simply cannot handle.

Enter Elasticsearch.

=== What is Elasticsearch?

[quote]
Elasticsearch is a search engine built on top of Apache Lucene.

So what is Lucene?

[quote,'http://lucene.apache.org/core/[lucene.apache.org/core]']
____
Apache Lucene(TM) is a high-performance, full-featured text search engine
library written entirely in Java.
____

Lucene is really, really powerful -- but it is just a library. If you want to
use Lucene, you must have a degree in information retrieval, work entirely in Java
and tightly couple your code to the Lucene libraries

Those are some pretty onerous constraints.

Elasticsearch aims to make full text search easy.  It is is based on Lucene,
which means that it uses Lucene internally for its indexing and search. Elasticsearch
enjoys all the power of Lucene for full text search.

However, it is much more than just Lucene and much more than ``just'' full
text search.

Elasticsearch is also:

* a distributed document store where every field is indexed and
   searchable
* a distributed search engine with real-time analytics
* capable of scaling to hundreds of servers and terabytes of structured
  and unstructured data.

And it packages up all of this functionality into a standalone service
that your application can talk to via a simple API.  Use
your favorite programming language, Elasticsearch doesn't care.

It is easy to get started with Elasticsearch. It ships with
sensible defaults and hides complicated search theory from beginners.
It _just works_, right out of the box. With minimal understanding,
you can soon become productive.

As your knowledge grows, you can leverage more of Elasticsearch's
advanced features. The entire engine is configurable and very flexible.
Pick and choose from the advanced features to tailor Elasticsearch to your
problem domain.

