[[_creating_an_index]]
=== 创建一个索引

到目前为止, 我们已经通过索引一篇文档创建了一个新的索引 ((("indices", "creating"))) 。这个索引采用的是默认的配置，新的字段通过动态映射的方式被添加到类型映射。现在我们需要对这个建立索引的过程做更多的控制：我们想要确保这个索引有数量适中的主分片，并且在我们索引任何数据 _之前_ ，分析器和映射已经被建立好。

为了达到这个目的，我们需要手动创建索引，在请求体里面传入设置或类型映射，如下所示：

[source,js]
--------------------------------------------------
PUT /my_index
{
    "settings": { ... any settings ... },
    "mappings": {
        "type_one": { ... any mappings ... },
        "type_two": { ... any mappings ... },
        ...
    }
}
--------------------------------------------------


如果你想禁止自动创建索引，你 ((("indices", "preventing automatic creation of"))) 可以通过在 `config/elasticsearch.yml` 的每个节点下添加下面的配置：

[source,js]
--------------------------------------------------
action.auto_create_index: false
--------------------------------------------------

[NOTE]
====
我们会在之后讨论你怎么用 <<index-templates>> 来预配置开启自动创建索引。这在索引日志数据的时候尤其有用：你将日志数据索引在一个以日期结尾命名的索引上，子夜时分，一个预配置的新索引将会自动进行创建。
====

=== 删除一个索引

用以下的请求来 ((("HTTP methods", "DELETE")))((("DELETE method", "deleting indices")))((("indices", "deleting"))) 删除索引:

[source,js]
--------------------------------------------------
DELETE /my_index
--------------------------------------------------


你也可以这样删除多个索引：

[source,js]
--------------------------------------------------
DELETE /index_one,index_two
DELETE /index_*
--------------------------------------------------


你甚至可以这样删除 _全部_ 索引：

[source,js]
--------------------------------------------------
DELETE /_all
DELETE /*
--------------------------------------------------

[NOTE]
====
对一些人来说，能够用单个命令来删除所有数据可能会导致可怕的后果。如果你想要避免意外的大量删除, 你可以在你的 `elasticsearch.yml` 做如下配置：

`action.destructive_requires_name: true`

这个设置使删除只限于特定名称指向的数据, 而不允许通过指定 `_all` 或通配符来删除指定索引库。你同样可以通过 <<_changing_settings_dynamically, Cluster State API>> 动态的更新这个设置。


====
