[[source-field]]
==== Metadata: _source Field
==== 메타데이터: _source 필드

By default, Elasticsearch ((("metadata, document", "_source field")))((("_source field", sortas="source field")))stores the JSON string representing the
document body in the `_source` field. Like all stored fields, the `_source`
field is compressed before being written to disk.

기본적으로 Elasticsearch는 ((("metadata, document", "_source field")))((("_source field", sortas="source field"))) 문서 바디를 나타내는 JSON 문자열을 `_source` 필드에 저장한다.
다른 모든 저장된 필드와 같이, `_source` 필드는 디스크에 기록되기 전에 압축된다.

This is almost always desired functionality because it means the following:

이것은 대부분의 경우 바람직한 동작인데, 그 이유는 다음과 같다.

* The full document is available directly from the search results--no need
  for a separate round-trip to fetch the document from another data store.

* 전체 문서를 검색 결과에서 직접 사용할 수 있다. 문서를 다른 데이터 저장소에서 가져오기 위한 별도의 라운드 트립이 필요하지 않다.

* Partial `update` requests will not function without the `_source` field.

* 부분적인 `update` 요청은 `_source` 필드 없이는 동작하지 않는다.

* When your mapping changes and you need to reindex your data, you can
  do so directly from Elasticsearch instead of having to retrieve all of your
  documents from another (usually slower) data store.

* 매핑이 변경되어 데이터를 재인덱싱 해야 할 때, 다른 (일반적으로 더 느린) 데이터 저장소에서 모든 데이터를 가져오지 않고도 Elasticsearch로부터 직접 재인덱싱을 할 수 있다.

* Individual fields can be extracted from the `_source` field and returned
  in `get` or `search` requests when you don't need to see the whole document.

* 개별 필드를 `_source` 필드에서 추출할 수 있으며, 문서 전체를 필요로 하지 않읊 때 `get` 또는 `search` 요청으로 개별 필드를 가져올 수도 있다.

* It is easier to debug queries, because you can see exactly what each document
  contains, rather than having to guess their contents from a list of IDs.

* ID의 목록에서 내용을 추측할 필요 없이 각 문서가 가진 내용을 확인할 수 있으므로 쿼리를 디버그 하기가 더 쉽다.

That said, storing the `_source` field does use disk space.  If none of the
preceding reasons is important to you, you can disable the `_source` field with
the following mapping:

하지만, `_source` 필드를 저장하려면 디스크 공간이 필요하다. 앞에서 나열한 이유들이 당신에게 중요하지 않다면, 다음 매핑을 통해 `_source` 필드를 비활성화 할 수 있다.

[source,js]
--------------------------------------------------
PUT /my_index
{
    "mappings": {
        "my_type": {
            "_source": {
                "enabled":  false
            }
        }
    }
}
--------------------------------------------------

In a search request, you can ask for only certain fields by specifying the
`_source` parameter in the request body:

검색을 요청할 때 다음과 같이 `_source` 파라미터를 요청 바디에 지정하여 특정한 필드에 대해서만 반환하도록 할 수도 있다.

[source,js]
--------------------------------------------------
GET /_search
{
    "query":   { "match_all": {}},
    "_source": [ "title", "created" ]
}
--------------------------------------------------
// SENSE: 070_Index_Mgmt/31_Source_field.json

Values for these fields will be extracted from the `_source` field and
returned instead of the full `_source`.

전체 `_source` 대신 이 검색에서 지정된 필드들에 대한 값만이 `_source` 필드에서 추출되어 반환될 것이다.

.Stored Fields
.저장된 필드
****

Besides indexing the values of a field, you ((("stored fields")))((("fields", "stored")))can also choose to `store` the
original field value for later retrieval. Users with a Lucene background use
stored fields to choose which fields they would like to be able to return in
their search results. In fact, the `_source` field is a stored field.

필드의 값을 인덱싱하는 것 이외에도, 이후의 조회를 위해 원래 필드 값을 `저장(store)`할 지 여부를 선택할 수 있다.((("stored fields")))((("fields", "stored")))
Lucene에 대한 배경 지식을 가진 사용자들은 검색 결과에서 어떤 것을 반환할 수 있는지를 선택할 때 저장된 필드를 사용한다. 사실, `_source` 필드는 저장된 필드이다.

In Elasticsearch, setting individual document fields to be stored is usually a
false optimization. The whole document is already stored as the `_source`
field. It is almost always better to just extract the fields that you need
by using the `_source` parameter.

일반적으로 Elasticsearch에서 개별 문서 필드가 저장되도록 설정하는 것은 최적화의 측면에서 보면 잘못된 것이다.
전체 문서는 이미 `_source` 필드로 저장되어 있다. `_source` 파라미터를 이용해 필요로 하는 필드만을 추출하는 것이 거의 항상 더 나은 방법이다.

****
