
==== Use not_analyzed for structured search

Since structured search is all about finding exact values, we want to make sure
that our values are being indexed without modification. Normally, when text is
indexed it will be run through an analysis process as discussed in 
<<analysis-intro>>.  Analysis will convert the text into something more easily 
found by *full-text* search 

*Structured search* is different because the user doesn't type the query
directly - they often interact with checkboxes or sliders, which are converted
into appropriate filters in the application.

For example, an e-commerce store may assign internal codes for t-shirt 
combinations (e.g. `tshirt_red_small`).  The user selects a checkbox representing
this option, and the application searches for `tshirt_red_small`.

The key is that `tshirt_red_small` is an exact enumeration that represents a
product.  We don't want to tokenize it into word tokens (`tshirt`, `red`, 
`small`).  That defeats our goal of structured search.

To prevent this behavior, we need tell Elasticsearch to avoid analyzing fields
that we wish to use for structured search.  This is done by setting `index:
not_analyzed` in the mapping for a particular field (see <<_customizing_field_mappings>> for more details).

