
==== Default values for null fields

By default, Elasticsearch ignores null values.  If a document is indexed with
a `null` as the value of a field, the field is simply not added to the document.

Sometimes this is inconvenient and you want to specify a default value. Most core
types (String, Number, Boolean, Date) support an option to define a null value
called, unsurprisingly, `null_value`.

In this mapping, we define a string as the default when a `null` is encountered:

[source,js]
--------------------------------------------------
{
   "tweet" : {
      "properties" : {
         "message" : {"type" : "string", "null_value" : "This is a default."}
      }
}
--------------------------------------------------


And now, when we index this document, the string "This is a default" will be 
indexed and stored in the `message` field:

[source,js]
--------------------------------------------------
{ "message" : null }    //Stored as { "message" : "This is a default." }
--------------------------------------------------


.Only works for explicit nulls!
****
An important note: this is a default that is applied _only_ when an explicit
null is provided as the value of a field.  It is not a default if the field
is omitted entirely.

If "message" is not present in the document at all, the default value _is not_
applied and no "message" field will be indexed.
****