
Filtering on ranges is a very common structured search. When dealing with numbers
in this chapter, we have so far only searched for exact numbers.  In practice, 
filtering on ranges tends to be more useful.  For example, find all products
with a price greater than $20 and less than $40.

In SQL terms, a range can be expressed as:

[source,sql]
--------------------------------------------------
SELECT document
FROM products
WHERE price BETWEEN 20 AND 40
--------------------------------------------------


Elasticsearch has a `range` filter, which, unsurprisingly, allows you to filter
ranges:

[source,js]
--------------------------------------------------
"range" : {
    "price" : {
        "gt" : 20 ,
        "lt" : 40
    } 
}
--------------------------------------------------

The `range` filter supports both inclusive and exclusive ranges, through
combinations of the following options:

 - `gt`: greater than (>), non-inclusive
 - `gte`: greater than or equal (>=), inclusive
 - `lt`: less than (<), non-inclusive
 - `lte`: less than or equal (<=), inclusive

Like every other filter we have seen in this chapter, the `range` filter is 
best used inside of a `filtered` query:

[source,js]
--------------------------------------------------
GET /my_store/products/_search
{
    "query" : {
        "filtered" : {
            "filter" : {
                "range" : { <1>
                    "price" : {
                        "gt" : 20,
                        "lt" : 40
                    } 
                }
            }
        }
    }
}
--------------------------------------------------
<1> The filter that we saw above, placed inside a `filtered` query

If you need an unbounded range (e.g. just `>20`), simply omit the one
of the boundaries:

[source,js]
--------------------------------------------------
GET /my_store/products/_search
{
    "query" : {
        "filtered" : {
            "filter" : {
                "range" : {
                    "price" : {
                        "gt" : 20 <1>
                    } 
                }
            }
        }
    }
}
--------------------------------------------------
<1> By omitting the `lt` clause, we have specified an unbounded `>20` range

==== Ranges on dates
The range filter also works on date fields.  Intuitively, we can specify the 
dates in our range:

[source,js]
--------------------------------------------------
GET /my_store/products/_search
{
    "query" : {
        "filtered" : {
            "query" : {},
            "filter" : {
                "range" : {
                    "timestamp" : {
                        "gt" : "2013-01-01 00:00:00",
                        "lt" : "2013-01-07 00:00:00"
                    } 
                }
            }
        }
    }
}
--------------------------------------------------

The date field also supports date math operations, which can be used in the
`range` filter.  For example, if we want to find all documents that have
a timestamp sometime in the last hour:

[source,js]
--------------------------------------------------
GET /my_store/products/_search
{
    "query" : {
        "filtered" : {
            "query" : {},
            "filter" : {
                "range" : {
                    "timestamp" : {
                        "gt" : "now-1h"
                    } 
                }
            }
        }
    }
}
--------------------------------------------------

This filter will now constantly find all documents with a timestamp greater than
the current time minus 1 hour, making the filter a "sliding window" across
your documents.

Date math can also be applied to actual dates, rather than a placeholder like
`now`.  For example, we ask for timestamps greater than a specified time:

[source,js]
--------------------------------------------------
GET /my_store/products/_search
{
    "query" : {
        "filtered" : {
            "query" : {},
            "filter" : {
                "range" : {
                    "timestamp" : {
                        "gt" : "2013-01-01 00:00:00",
                        "lt" : "2013-01-01 00:00:00||+1M"
                    } 
                }
            }
        }
    }
}
--------------------------------------------------

Simply separate the date from the date math with a double pipe (`||`).  In this
example, we asked for all documents in the month of January (`+1M` specifies
one month).

Date math is "calendar aware", so it knows how many days are in each month, 
days in a year, etc.

==== Ranges on strings
The range filter can also operate on string fields.  String ranges are 
calculated lexicographically (aka alphabetically).  For example, these values
are sorted in lexicographic order:

 - `a`
 - `ab`
 - `abb`
 - `abc`
 - `b`

If we want a range from `ab` to `abc`, we can use the same `range` filter
syntax:

[source,js]
--------------------------------------------------
GET /my_store/products/_search
{
    "query" : {
        "filtered" : {
            "query" : {},
            "filter" : {
                "range" : {
                    "title" : {
                        "gt" : "ab",
                        "lt" : "abc"
                    } 
                }
            }
        }
    }
}
--------------------------------------------------

.Be careful of cardinality
****
Ranges on string values are inherently slower than numeric ranges, which seems
pretty obvious.  Finding ranges on numbers/dates is a trivial operation, while
comparing strings requires many more operations.

In general, just remember that the higher your field's cardinality (e.g. the
number of unique values in the field), the slower a string range will be.
****

