[[intro]]
== You know, for Search...

// For the general introduction of ES I think maybe a few things could be added:
// 1) It is written in Java
// 2) It is licensed under Apache 2
// 3) Maybe one or two sentences explaining the history of the project:
// When was it started? By whom? Why? Even if the point is not about personifying 
// the project too much. It is always nice to have a bit of background information
// and it could be stated here that the project has a few hundreds contributors worldwide.

Elasticsearch is a search engine built on top of
https://lucene.apache.org/core/[Apache Lucene(TM)] , a full-text search engine
library.  Lucene is arguably the most advanced, performant and fully-featured
search engine library in existence today -- both open source and proprietary.

But, Lucene is just a library. To leverage its power you need to work in Java
and to integrate Lucene directly with your application. Worse, you will likely
require a degree in Information Retrieval to understand how it works.  Lucene
is *very* complex.

Elasticsearch uses Lucene internally for all of its indexing and search, but
it aims to make full text search easy by hiding the complexities of Lucene
behind a simple, coherent API.

However, Elasticsearch is much more than just Lucene and much more than
``just'' full text search. It is also:

* a distributed real-time document store where *every field* is indexed and
   searchable
* a distributed search engine with real-time analytics
* capable of scaling to hundreds of servers and petabytes of structured
  and unstructured data.

And it packages up all of this functionality into a standalone server that
your application can talk to via a simple RESTful API, using a web client from
your favorite programming language, or even from the command line.

It is easy to get started with Elasticsearch. It ships with sensible defaults
and hides complicated search theory away from beginners. It _just works_,
right out of the box. With minimal understanding, you can soon become
productive.

// Maybe it could be nice to add near "very flexible" pluginable.
// That would introduce a bit the incoming Marvel just after

As your knowledge grows, you can leverage more of Elasticsearch's advanced
features. The entire engine is configurable and very flexible. Pick and choose
from the advanced features to tailor Elasticsearch to your problem domain.

