[[intro]]
== 你懂得的，关于搜索的秘密...

Elasticsearch是一个基于Lucence开源的全文搜索引擎。Lucene不论在开源或闭源界都称得上是最高级、高效且功能完备的搜索引擎库。
但Lucene仅仅只是一个库。想要真正发挥它的能力你需要借助Java将它直接应用到您的项目中。更糟的是，你将会花大量精力来理解它是如何工作的。因为，Lucene极其复杂。

Elasticsearch同样是由Java编写并且所有的索引和搜索功能全部基于Lucene，但它把复杂的Lucene隐藏在了简洁的RESTful API的后面。

然而，Elasticsearch不仅仅是Lucene且远远不至于全文搜索。Elasticsearch是:

* 分布式的实时文档数据库(document store)，每一个字段都被索引并且可搜索。
* 有实时分析功能的分布式搜索引擎
* 可伸缩至上百上千台服务器支持peta级别的结构和非结构化数据


原文：
[[intro]]
== You Know, for Search...

Elasticsearch is an open-source search engine built on top of
https://lucene.apache.org/core/[Apache Lucene(TM)], a full-text search-engine
library.((("Apache Lucene")))((("Lucene")))  Lucene is arguably the most advanced, high-performance, and fully featured
search engine library in existence today--both open source and proprietary.

But Lucene is just a library. To leverage its power, you need to work in Java
and to integrate Lucene directly with your application. Worse, you will likely
require a degree in information retrieval to understand how it works.  Lucene
is _very_ complex.

Elasticsearch is also written in Java((("Java"))) and uses Lucene internally for all of
its indexing and searching, but it aims to make full-text search easy by hiding
the complexities of Lucene behind a simple, coherent, RESTful API.

However, Elasticsearch is much more than just Lucene and much more than
``just'' full-text search.((("Elasticsearch", "capabilities"))) It can also be described as follows:

* A distributed real-time document store where _every field_ is indexed and
  searchable
* A distributed search engine with real-time analytics
* Capable of scaling to hundreds of servers and petabytes of structured
  and unstructured data

And it packages up all this functionality into a standalone server that
your application can talk to via a simple RESTful API, using a web client from
your favorite programming language, or even from the command line.

It is easy to get started with Elasticsearch. It ships with sensible defaults
and hides complicated search theory away from beginners. It _just works_,
right out of the box. With minimal understanding, you can soon become
productive.((("Elasticsearch", "installing")))

Elasticsearch can be((("Apache 2 license"))) downloaded, used, and modified free of charge. It is
available under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2 license],
one of the most flexible open source licenses available.

As your knowledge grows, you can leverage more of Elasticsearch's advanced
features. The entire engine is configurable and flexible. Pick and choose
from the advanced features to tailor Elasticsearch to your problem domain.

.The Mists of Time
***************************************

Many years ago, a newly married unemployed developer called Shay Banon
followed his wife to London, where she was studying to be a chef. While looking
for gainful employment, he started playing with an early version of Lucene,
with the intent of building his wife a recipe search engine.

Working directly with Lucene can be tricky, so Shay started work on an
abstraction layer to make it easier for Java programmers to add search to
their applications.  He released this as his first open source project, called
Compass.

Later Shay took a job working in a high-performance, distributed environment
with in-memory data grids.  The need for a high-performance, real-time,
distributed search engine was obvious, and he decided to rewrite the Compass
libraries as a standalone server called Elasticsearch.

The first public release came out in February 2010.  Since then, Elasticsearch
has become one of the most popular projects on GitHub with commits from over
300 contributors.  A company has formed around Elasticsearch to provide
commercial support and to develop new features, but Elasticsearch is, and
forever will be, open source and available to all.

Shay's wife is still waiting for the recipe search...

***************************************
