[[intro]]
== You know, for Search...

Elasticsearch is a search engine built on top of
https://lucene.apache.org/core/[Apache Lucene(TM)] , a full-text search engine
library.  Lucene is arguably the most advanced, performant and fully-featured
search engine library in existence today -- open source or proprietary.

But, Lucene is just a library. To leverage its power requires using Java
to integrate it into your application. Worse, you will likely
require a degree in Information Retrieval to understand how it works.  Lucene
is *very* complex.

Elasticsearch uses Lucene internally to do its indexing and search, but
attempts to simplify full text search by hiding Lucene's complexity
behind a simple, coherent API.

However, Elasticsearch is much more than just Lucene and much more than
``just'' full text search. It is also:

* a distributed real-time document store where *every field* is indexed and
   searchable
* a distributed search engine with real-time analytics
* capable of scaling to hundreds of servers and petabytes of structured
  and unstructured data.

Elasticsearch packages up all of this into a standalone server that
your application can talk to via a simple RESTful API, using any web client
written in any programming language, or even from the command line.

It is easy to get started with Elasticsearch. It's configured with sensible defaults
and hides complicated search theory from beginners. It _just works_,
right out of the box. You can soon become
productive with minimal effort.

As your knowledge grows, you can leverage more of Elasticsearch's advanced
features. The entire engine is configurable and very flexible. Pick and choose
advanced features to tailor Elasticsearch to your problem.

