=== Gettting started

The easiest way to understand what Elasticsearch can do for you is to
play with it, so let's get started!

The only requirement for installing Elasticsearch is a recent version of Java.
Preferably, you should install the latest version of the official Java
from http://www.java.com[www.java.com].

Now you can download the latest version of Elasticsearch from
http://www.elasticsearch.org/download/.

[source,js]
--------------------------------------------------
curl -L -O http://download.elasticsearch.org/PATH/TO/LATEST/$VERSION.zip
unzip elasticsearch-$VERSION.zip
cd  elasticsearch-$VERSION
--------------------------------------------------

Elasticsearch is now ready to run. You can start it up in the foreground
with:

[source,js]
--------------------------------------------------
./bin/elasticsearch <1>
--------------------------------------------------
<1> Add `-d` if you want to run it in the background as a daemon.

Test it out by opening another terminal window and running:

[source,js]
--------------------------------------------------
curl 'http://localhost:9200/?pretty'
--------------------------------------------------


You should see a response like this:

[source,js]
--------------------------------------------------
{
   "status": 200,
   "name": "Shrunken Bones",
   "version": {
      "number": "1.0.0",
      "lucene_version": "4.6"
   },
   "tagline": "You Know, for Search"
}
--------------------------------------------------

This means that your Elasticsearch _cluster_ is up and running, and we can
start experimenting with it.

.Clusters and nodes
****

A _node_ is a running instance of Elasticsearch. A _cluster_ is a group of
nodes with the same `cluster.name` that are working together to share data,
and to provide failover and scale, although a single node can form a cluster
all by itself.

****
