=== Installing Elasticsearch

The easiest way to understand what Elasticsearch can do for you is to
play with it, so let's get started!

The only requirement for installing Elasticsearch is a recent version of Java.
Preferably, you should install the latest version of the official Java
from http://www.java.com[www.java.com].

You can download the latest version of Elasticsearch from
http://www.elasticsearch.org/download/[elasticsearch.org/download].

[source,sh]
--------------------------------------------------
curl -L -O http://download.elasticsearch.org/PATH/TO/LATEST/$VERSION.zip
unzip elasticsearch-$VERSION.zip
cd  elasticsearch-$VERSION
--------------------------------------------------

TIP: When installing Elasticsearch in production, you can use the method
described above, or the Debian or RPM packages provided on the
http://www.elasticsearch.org/downloads[downloads page]. You can also use
the officially supported
https://github.com/elasticsearch/puppet-elasticsearch[Puppet module] or
https://github.com/elasticsearch/cookbook-elasticsearch[Chef cookbook].

[[marvel]]
==== Installing Marvel

http://www.elasticsearch.com/marvel[Marvel] is a management and monitoring
tool for Elasticsearch which is free for development use. It comes with an
interactive console called Sense which makes it very easy to talk to
Elasticsearch directly from your browser.

Many of the code examples in this book include a ``View in Sense'' link. When
clicked, it will open up a working example of the code in the Sense console.
You do not have to install Marvel, but it will make this book much more
interactive by allowing you to  experiment with the code samples on your local
Elasticsearch cluster.

Marvel is available as a plugin. To download and install it, run this command
in the Elasticsearch directory:

[source,sh]
--------------------------------------------------
./bin/plugin -i elasticsearch/marvel/latest
--------------------------------------------------

You probably don't want Marvel to monitor your local cluster, so you can
disable data collection with this command:

[source,sh]
--------------------------------------------------
echo 'marvel.agent.enabled: false' >> ./config/elasticsearch.yml
--------------------------------------------------

=== Running Elasticsearch

Elasticsearch is now ready to run. You can start it up in the foreground
with:

[source,sh]
--------------------------------------------------
./bin/elasticsearch
--------------------------------------------------
Add `-d` if you want to run it in the background as a daemon.

Test it out by opening another terminal window and running:

[source,sh]
--------------------------------------------------
curl 'http://localhost:9200/?pretty'
--------------------------------------------------


You should see a response like this:

[source,js]
--------------------------------------------------
{
   "status": 200,
   "name": "Shrunken Bones",
   "version": {
      "number": "1.1.0",
      "lucene_version": "4.7"
   },
   "tagline": "You Know, for Search"
}
--------------------------------------------------
// SENSE: 010_Intro/10_Info.json

This means that your Elasticsearch _cluster_ is up and running, and we can
start experimenting with it.

.Clusters and nodes
****

A _node_ is a running instance of Elasticsearch. A _cluster_ is a group of
nodes with the same `cluster.name` that are working together to share data
and to provide failover and scale, although a single node can form a cluster
all by itself.

****
