=== Multi-tenancy

Elasticsearch supports _multi-tenancy_. In other words, just like a relational
database can have multiple independent ``databases'', Elasticsearch can have
multiple independent indices. We can run multiple applications, potentially
with very different search requirements, with a single Elasticsearch cluster.

Similarly, each index can have multiple types, each with its own mapping or
schema.

Unlike a relational database, Elasticsearch can search across
multiple types, and across multiple indices. Simply include another index
in the URI to search both at the same time:

[source,js]
--------------------------------------------------
GET /blogs,blogs2/_search
--------------------------------------------------


Later, you will see how the ability to search across multiple indices as if
they were one, allows us to scale out as our requirements grow.

.Gimmick?
****

Searching across indices may seem like a gimmick at first glance, but it
actually allows for some very high-performance optimizations. Consider data
that is stored in a new index each day. Searching the last seven days is as
simple as including the last seven indices in the URI, avoiding the need to
look through the rest of the indices altogether. And expiring old data
is as easy as deleting an index.

****

