[[geo-shapes]]
== Geo-shapes

Geo-shapes use a completely different approach to geo-points. A circle on a
computer screen does not consist of a perfect continuous line. Instead it is
drawn by colouring adjacent pixels as an approximation of a circle. Geo-shapes
work in much the same way.

Complex shapes -- points, lines, polygons, multi-polygons, polygons with
holes, etc -- are ``painted'' onto a grid of geohash cells, and the shape is
converted into a list of the geohashes of all the cells that it touches.

.Quad trees
***************************************

Actually, there are two types of grids that can be used with geo-shapes:
geohashes, which we have already discussed and which are the default encoding,
and _quad trees_.  Quad trees are similar to geohashes except that there are
only four cells at each level, instead of 32.  The difference comes down to a
choice of encoding.

***************************************


All of the geohashes that comprise a shape are indexed as if they were terms.
With this information in the index, it is easy to determine whether one shape
intersects with another, as they will share the same geohash terms.

That is the extent of what you can do with geo-shapes: determine the
relationship between a query shape and a shape in the index.  The `relation`
can be one of:

`intersects`::

    The query shape overlaps with the indexed shape. (default)

`disjoint`::

    The query shape does *not* overlap at all with the indexed shape.

`within`::

    The indexed shape is entirely within the query shape.

Geo-shapes cannot be used to caculate distance, they cannot be used for
sorting or scoring, and they cannot be used in aggregations.

