[[language-intro]]
== Getting Started with Languages

Elasticsearch ships with a collection of language analyzers that provide
good, basic, https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html[out-of-the-box support]
for many of the world's most common languages.

These analyzers typically perform four roles:

* Tokenize text into individual words:
+
`The quick brown foxes` -> [`The`, `quick`, `brown`, `foxes`]

* Lowercase tokens:
+
`The` -> `the`

* Remove common _stopwords_:
+
&#91;`The`, `quick`, `brown`, `foxes`] -> [`quick`, `brown`, `foxes`]

* Stem tokens to their root form:
+
`foxes` -> `fox`

Each analyzer may also apply other transformations specific to its language in
order to make words from that language more searchable:

* The `english` analyzer removes the possessive `'s`:
+
`John's` -> `john`

* The `french` analyzer removes _elisions_ like `l'` and `qu'` and
  _diacritics_ like `¨` or `^`:
+
`l'église` -> `eglis`

* The `german` analyzer normalizes terms, replacing `ä` and `ae` with `a`, or
  `ß` with `ss`, among others:
+
`äußerst` -> `ausserst`
