[[range_filter]]
=== `range` filters

A `range` filter is used to match fields which contain values within a certain
range, for instance:

    {
        "range" : {
            "created" : {
                "from" :  "2011-01-01",
                "to" :    "2012-01-01"
        }
    }

Ranges can also be applied to string fields:

    {
        "range" : {
            "title" : {
                "from" :  "apple",
                "to" :    "orange"
        }
    }

The comparison operators are as follows:

`gte`:: Greater than or equal to
`gt`:: Greater than
`lte`:: Less then or equal to
`lt`:: Less than
`from`:: The same as `gte`
`to`:: The same as `lt` (*not* `lte`)

The `to` operator means _up to but not including_, so a range
of `{ "from" : 0, "to" : 100 }` includes the range `0..99`, not `0..100`.

[[numeric_range_filter]]
==== Numeric range filter

    {
        "numeric_range" : {
            "last_modified" : {
                "from" :  "2012-01-01 00:00:00",
                "to" :    "2012-01-01 01:00:00"
        }
    }

The `numeric_range` filter is a special type of `range` filter which may
perform better for:

* fields which have many many values, e.g. a `timestamp` field
* fields that are also being used to sort results

The first time that a `numeric_range` filter is used, elasticsearch
has to build a _field cache_, which caches all the values for that field in
memory.  Building the field cache can be slow, but once it is built it can
make future `numeric_range` filters faster.
