

=== One Final Modification

Just to drive the point home, let's make one final modification to our example
before moving on to new topics. Let's add two metrics to calculate the min and
max tip per ride for each passenger count:


[source,js]
--------------------------------------------------
GET /taxis/_search
{
  "size": 0,
  "aggs": {
    "vendors": {
      "terms": {
        "field": "vendor"
      },
      "aggs": {
        "avg_revenue": {
          "avg": {
            "field": "total_amount"
          }
        },
        "passengers": {
          "terms": {
            "field": "passenger_count"
          },
          "aggs": { <1>
            "min_tip": { "min": { "field": "tip_amount" } }, <2>
            "max_tip": { "max": { "field": "tip_amount" } }  <3>
          }
        }
      }
    }
  }
}
--------------------------------------------------
// CONSOLE: 300_Aggregations/20_basic_example.json

<1> We need to add another `aggs` level for nesting.
<2> Then we include a `min` metric.
<3> And a `max` metric.

Which gives us the following output (again, truncated):

[source,js]
--------------------------------------------------
{
  ...
  "aggregations": {
    "vendors": {
      ...
      "buckets": [
        {
          "key" : "Black",
          "doc_count" : 49862,
          "passengers" : {
            ...
            "buckets" : [
              {
                "key" : 1,
                "doc_count" : 32819,
                "min_tip" : {
                  "value" : 0.0 <1>
                },
                "max_tip" : {
                  "value" : 9.18 <1>
                }
              },
              {
                "key" : 2,
                "doc_count" : 8128,
                "min_tip" : {
                  "value" : 0.0
                },
                "max_tip" : {
                  "value" : 9.18
                }
              },
              {
                "key" : 3,
                "doc_count" : 3728,
                "min_tip" : {
                  "value" : 0.0
                },
                "max_tip" : {
                  "value" : 9.0
                }
              },
              {
                "key" : 5,
                "doc_count" : 3278,
                "min_tip" : {
                  "value" : 0.0
                },
                "max_tip" : {
                  "value" : 8.82
                }
              },
              {
                "key" : 4,
                "doc_count" : 1909,
                "min_tip" : {
                  "value" : 0.0
                },
                "max_tip" : {
                  "value" : 9.0
                }
              }
            ]
          },
          "avg_revenue" : {
            "value" : 22.613874092495085
          }
        },
        ...
      ]
    }
  }
}
--------------------------------------------------
<1> The `min` and `max` metrics that we added now appear under each `passengers` count.

With those two buckets, we've expanded the information derived from this query
to include the following:

- There are five different taxi vendors.
- The average revenue per ride of the "Black" vendor is $22.61.
- Most of the time (32,819 out of a total 49,862) they have only one passenger.
- Single passengers give no tip or tip up to $9.18.